# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32-GUI-XMLBuilder
version:      0.37
version_from: lib/Win32/GUI/XMLBuilder.pm
installdirs:  site
requires:
    Win32::GUI:                    0.0.671
    XML::Twig:                     3.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
